name: binder-badge

on:
  pull_request_target:

permissions:
  issues: write

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: manics/action-binderbadge@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
